# Set to true to add reviewers to pull requests
addReviewers: false

# Set to true to add assignees to pull requests
addAssignees: author

# Set to true to add reviewers from different groups to pull requests
useReviewGroups: false
